// <auto-generated />
namespace PMQLKSCK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creata_Table_DichVus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creata_Table_DichVus));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131306543_Creata_Table_DichVus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
