// <auto-generated />
namespace PMQLKSCK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creata_Table_NhanViens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creata_Table_NhanViens));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131300389_Creata_Table_NhanViens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
